# Generated by Django 6.0.3 on 2026-03-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_question_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
